name: potless
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  kakao_map_plugin: ^0.3.0
  kakao_flutter_sdk_common: ^1.9.1+2

  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  carousel_slider: ^4.2.1

  camera: ^0.10.5+9
  video_player: ^2.8.6
  path_provider: ^2.1.3
  image_picker: ^1.1.0
  photo_gallery: ^2.2.1
  
  # 욜로 ai 넣기
  tflite_flutter: ^0.10.4
  image: ^4.1.7
  exif: ^3.3.0

  # 좌표
  geolocator: ^11.0.0
  
  # S3 이미지 업로드용 
  amplify_flutter: ^0.5.1
  amplify_auth_cognito: ^0.5.1
  amplify_storage_s3: ^0.5.1

  # http 요청
  http: ^1.2.1
  intl: ^0.19.0
  external_path: ^1.0.3
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/pothole/
    - assets/icons/
    - assets/lottie/
    - assets/dummy_data/
    - assets/ai_model/
  
  fonts:
    - family: 'Hanbit'
      fonts:
        - asset: assets/fonts/KCC-Hanbit/KCC-Hanbit.ttf

    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 900

    - family: Spoqa
      fonts:
        - asset: assets/fonts/Spoqa/SpoqaHanSansNeo-Regular.ttf
        - asset: assets/fonts/Spoqa/SpoqaHanSansNeo-Bold.ttf
          weight: 900