spring:
  profiles:
    active: dev
    include:
      - jwt
      - filter
      - mail
      - db
      - kakao
      - aws

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

---
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

cors:
  allowed:
    origins: "*"

server:
  port: 7080

---
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace